name: Deploy to Salesforce by branch wies

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Salesforce CLI
      run: |
        sudo npm install -g sfdx-cli
        sfdx --version

    - name: Authenticate to Production Org (Main Branch)
      if: github.ref == 'refs/heads/main'
      env:
        SF_USERNAME: ${{ secrets.SF_SANDBOX_USERNAME }}
        SF_CONSUMER_KEY: ${{ secrets.SF_CONSUMER_KEY }}
        SF_PRIVATE_KEY: ${{ secrets.SF_PRIVATE_KEY }}
        SF_LOGIN_URL: https://login.salesforce.com  # Production login URL
      run: |
        echo "$SF_PRIVATE_KEY" > server.key
        sfdx force:auth:jwt:grant --clientid $SF_CONSUMER_KEY --jwtkeyfile server.key --username $SF_USERNAME --instanceurl $SF_LOGIN_URL

    - name: Authenticate to Sandbox Org (Dev Branch)
      if: github.ref == 'refs/heads/dev'
      env:
        SF_USERNAME: ${{ secrets.SF_AI_USERNAME }}
        SF_CONSUMER_KEY: ${{ secrets.AI_SANDBOX_CLIENTID }}
        SF_PRIVATE_KEY: ${{ secrets.AI_SANDBOX_PRIVATEKEY }}
        SF_LOGIN_URL: https://test.salesforce.com  # Sandbox login URL
      run: |
        echo "$SF_PRIVATE_KEY" > jwt.key
        sfdx force:auth:jwt:grant --clientid $SF_CONSUMER_KEY --jwtkeyfile jwt.key --username $SF_USERNAME --instanceurl $SF_LOGIN_URL

    - name: Deploy to Salesforce
      run: |
        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          echo "Deploying to Production Org"
          sfdx force:source:deploy -p force-app -u ${{ secrets.SF_SANDBOX_USERNAME }} --json --loglevel debug > deploy.log
        elif [ "${{ github.ref }}" == "refs/heads/dev" ]; then
          echo "Deploying to Sandbox Org"
          sfdx force:source:deploy -p manifest/package.xml -u ${{ secrets.SF_AI_USERNAME }} --json --loglevel debug > deploy.log
        fi

        # Check if the deployment succeeded
        if [ $? -eq 0 ]; then
          echo "Deployment succeeded!"
        else
          echo "Deployment failed. Check the logs below:"
          cat deploy.log
          exit 1
        fi
